services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    env_file: .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    restart: on-failure
    expose:
      - "3306"

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    env_file: .env
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    restart: on-failure
    expose:
      - "9000"

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    env_file: .env
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    restart: on-failure

volumes:
  mariadb_data:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/tpipi/data/mariadb
      o: bind
      type: none

  wordpress_data:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/tpipi/data/wordpress
      o: bind
      type: none

networks:
  inception:
    driver: bridge
