CREATE DATABASE IF NOT EXISTS '${DB_NAME}';
CREATE USER IF NOT EXISTS '${DB_USER}'@'%' IDENTIFIED BY '${DB_UPWD}';
GRANT ALL PRIVILEGES ON '${DB_NAME}'.* TO '${DB_USER}'@'%';
ALTER USER 'root'@'localhost' IDENTIFIED BY '${DB_ROOTPWD}';
FLUSH PRIVILEGES;
